generatorName: rust
templateDir: template
useSingleRequestParameter: true
preferUnsignedInt: true
basePathCustom: https://api.artifactsmmo.com
operationIdNameMappings:
  actionMoveMyNameActionMovePost: move_character
  actionEquipItemMyNameActionEquipPost: equip_item
  actionUnequipItemMyNameActionUnequipPost: unequip_item
  actionFightMyNameActionFightPost: fight
  actionGatheringMyNameActionGatheringPost: gather
  actionCraftingMyNameActionCraftingPost: craft
  actionDepositBankMyNameActionBankDepositPost: deposit_item
  actionDepositBankGoldMyNameActionBankDepositGoldPost: deposit_gold
  actionRecyclingMyNameActionRecyclingPost: recycle
  actionWithdrawBankMyNameActionBankWithdrawPost: withdraw_item
  actionWithdrawBankGoldMyNameActionBankWithdrawGoldPost: withdraw_gold
  actionGeBuyItemMyNameActionGeBuyPost: ge_buy_item
  actionGeSellItemMyNameActionGeSellPost: ge_sell_item
  actionBuyBankExpansionMyNameActionBankBuyExpansionPost: buy_bank_expansion
  actionAcceptNewTaskMyNameActionTaskNewPost: accept_new_task
  actionCompleteTaskMyNameActionTaskCompletePost: complete_task
  actionTaskExchangeMyNameActionTaskExchangePost: task_exchange
  actionTaskCancelMyNameActionTaskCancelPost: cancel_task
  actionDeleteItemMyNameActionDeletePost: delete_item
  getAllCharactersLogsMyLogsGet: get_all_characters_logs
  getMyCharactersMyCharactersGet: get_my_characters
  getBankDetailsMyBankGet: get_bank_details
  getBankItemsMyBankItemsGet: get_bank_items
  changePasswordMyChangePasswordPost: change_password
  createCharacterCharactersCreatePost: create_character
  deleteCharacterCharactersDeletePost: delete_character
  getAllCharactersCharactersGet: get_all_characters
  getCharacterCharactersNameGet: get_character
  getCharacterAchievementsCharactersNameAchievementsGet: get_character_achievements
  getAllMapsMapsGet: get_all_maps
  getMapMapsXYGet: get_map
  getAllItemsItemsGet: get_all_items
  getItemItemsCodeGet: get_item
  getAllMonstersMonstersGet: get_all_monsters
  getMonsterMonstersCodeGet: get_monster
  getAllResourcesResourcesGet: get_all_resources
  getResourceResourcesCodeGet: get_resource
  getAllEventsEventsGet: get_all_events
  getAllGeItemsGeGet: get_all_ge_items
  getGeItemGeCodeGet: get_ge_item
  getAllAchievementsAchievementsGet: get_all_achievements
  getAchievementAchievementsCodeGet: get_achievement
  getLeaderboardLeaderboardGet: get_leaderboard
  createAccountAccountsCreatePost: create_account
  generateTokenTokenPost: generate_token
  getStatusGet: get_status
